package com.web.bl.model;
// Generated Sep 17, 2018 10:15:01 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerProduct generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "CUSTOMER_PRODUCT", schema = "EADDRESS")
public class CustomerProduct implements java.io.Serializable {

	private BigDecimal custProdId;
	private String prodName;
	private String active;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public CustomerProduct() {
	}

	public CustomerProduct(BigDecimal custProdId, String prodName) {
		this.custProdId = custProdId;
		this.prodName = prodName;
	}

	public CustomerProduct(BigDecimal custProdId, String prodName, String active, Date createdDate, String createdBy,
			Date updatedDate, String updatedBy) {
		this.custProdId = custProdId;
		this.prodName = prodName;
		this.active = active;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id

	@Column(name = "CUST_PROD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCustProdId() {
		return this.custProdId;
	}

	public void setCustProdId(BigDecimal custProdId) {
		this.custProdId = custProdId;
	}

	@Column(name = "PROD_NAME", nullable = false, length = 100)
	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	@Column(name = "ACTIVE", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UPDATED_BY", length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
