package com.web.bl.model;
// Generated May 7, 2018 2:52:16 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERS", schema = "EADDRESS")
public class Customers implements java.io.Serializable {

	private BigDecimal CId;
	private String msisdn;
	private String product;
	private String billCycle;
	private String media;
	private String iscommunicated;
	private String interestedforebill;
	private String interestedforcourier;
	private String updateby;
	private Date updatedate;
	private String createdby;
	private Date createddate;
	private String cnc;
	private String flag1;
	private String flag2;
	private String flag3;
	private String flag4;
	private String flag5;
	private String active;
	private String customerSecret;
	private Set<CustomersEmailAddress> customersEmailAddresses = new HashSet<CustomersEmailAddress>(0);

	public Customers() {
	}

	public Customers(BigDecimal CId) {
		this.CId = CId;
	}

	public Customers(BigDecimal CId, String msisdn, String product, String billCycle, String media,
			String iscommunicated, String interestedforebill, String interestedforcourier, String updateby,
			Date updatedate, String createdby, Date createddate, String cnc, String flag1, String flag2, String flag3,
			String flag4, String flag5, String active, String customerSecret,
			Set<CustomersEmailAddress> customersEmailAddresses) {
		this.CId = CId;
		this.msisdn = msisdn;
		this.product = product;
		this.billCycle = billCycle;
		this.media = media;
		this.iscommunicated = iscommunicated;
		this.interestedforebill = interestedforebill;
		this.interestedforcourier = interestedforcourier;
		this.updateby = updateby;
		this.updatedate = updatedate;
		this.createdby = createdby;
		this.createddate = createddate;
		this.cnc = cnc;
		this.flag1 = flag1;
		this.flag2 = flag2;
		this.flag3 = flag3;
		this.flag4 = flag4;
		this.flag5 = flag5;
		this.active = active;
		this.customerSecret = customerSecret;
		this.customersEmailAddresses = customersEmailAddresses;
	}

	@Id

	@Column(name = "C_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCId() {
		return this.CId;
	}

	public void setCId(BigDecimal CId) {
		this.CId = CId;
	}

	@Column(name = "MSISDN", length = 10)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "PRODUCT", length = 20)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "BILL_CYCLE", length = 20)
	public String getBillCycle() {
		return this.billCycle;
	}

	public void setBillCycle(String billCycle) {
		this.billCycle = billCycle;
	}

	@Column(name = "MEDIA", length = 50)
	public String getMedia() {
		return this.media;
	}

	public void setMedia(String media) {
		this.media = media;
	}

	@Column(name = "ISCOMMUNICATED", length = 10)
	public String getIscommunicated() {
		return this.iscommunicated;
	}

	public void setIscommunicated(String iscommunicated) {
		this.iscommunicated = iscommunicated;
	}

	@Column(name = "INTERESTEDFOREBILL", length = 10)
	public String getInterestedforebill() {
		return this.interestedforebill;
	}

	public void setInterestedforebill(String interestedforebill) {
		this.interestedforebill = interestedforebill;
	}

	@Column(name = "INTERESTEDFORCOURIER", length = 10)
	public String getInterestedforcourier() {
		return this.interestedforcourier;
	}

	public void setInterestedforcourier(String interestedforcourier) {
		this.interestedforcourier = interestedforcourier;
	}

	@Column(name = "UPDATEBY", length = 50)
	public String getUpdateby() {
		return this.updateby;
	}

	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDATE", length = 7)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "CREATEDBY", length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "CNC", length = 20)
	public String getCnc() {
		return this.cnc;
	}

	public void setCnc(String cnc) {
		this.cnc = cnc;
	}

	@Column(name = "FLAG1", length = 20)
	public String getFlag1() {
		return this.flag1;
	}

	public void setFlag1(String flag1) {
		this.flag1 = flag1;
	}

	@Column(name = "FLAG2", length = 20)
	public String getFlag2() {
		return this.flag2;
	}

	public void setFlag2(String flag2) {
		this.flag2 = flag2;
	}

	@Column(name = "FLAG3", length = 20)
	public String getFlag3() {
		return this.flag3;
	}

	public void setFlag3(String flag3) {
		this.flag3 = flag3;
	}

	@Column(name = "FLAG4", length = 20)
	public String getFlag4() {
		return this.flag4;
	}

	public void setFlag4(String flag4) {
		this.flag4 = flag4;
	}

	@Column(name = "FLAG5", length = 20)
	public String getFlag5() {
		return this.flag5;
	}

	public void setFlag5(String flag5) {
		this.flag5 = flag5;
	}

	@Column(name = "ACTIVE", length = 10)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CUSTOMER_SECRET", length = 128)
	public String getCustomerSecret() {
		return this.customerSecret;
	}

	public void setCustomerSecret(String customerSecret) {
		this.customerSecret = customerSecret;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	public Set<CustomersEmailAddress> getCustomersEmailAddresses() {
		return this.customersEmailAddresses;
	}

	public void setCustomersEmailAddresses(Set<CustomersEmailAddress> customersEmailAddresses) {
		this.customersEmailAddresses = customersEmailAddresses;
	}

}
