package com.web.bl.model;
// Generated Sep 6, 2018 5:02:51 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dropdown generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DROPDOWN", schema = "EADDRESS")
//@Table(name = "DROPDOWN", schema = "ADMIN")
public class Dropdown implements java.io.Serializable {

	private BigDecimal ddId;
	private String ddName;
	private String label;
	private String id;
	private BigDecimal ddSerial;
	private String ddActive;

	public Dropdown() {
	}

	public Dropdown(BigDecimal ddId) {
		this.ddId = ddId;
	}

	public Dropdown(BigDecimal ddId, String ddName, String label, String id, BigDecimal ddSerial, String ddActive) {
		this.ddId = ddId;
		this.ddName = ddName;
		this.label = label;
		this.id = id;
		this.ddSerial = ddSerial;
		this.ddActive = ddActive;
	}

	@Id

	@Column(name = "DD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getDdId() {
		return this.ddId;
	}

	public void setDdId(BigDecimal ddId) {
		this.ddId = ddId;
	}

	@Column(name = "DD_NAME", length = 50)
	public String getDdName() {
		return this.ddName;
	}

	public void setDdName(String ddName) {
		this.ddName = ddName;
	}

	@Column(name = "LABEL", length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "ID", length = 100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "DD_SERIAL", precision = 22, scale = 0)
	public BigDecimal getDdSerial() {
		return this.ddSerial;
	}

	public void setDdSerial(BigDecimal ddSerial) {
		this.ddSerial = ddSerial;
	}

	@Column(name = "DD_ACTIVE", length = 10)
	public String getDdActive() {
		return this.ddActive;
	}

	public void setDdActive(String ddActive) {
		this.ddActive = ddActive;
	}

}
