package com.web.bl.model;
// Generated Apr 19, 2018 12:23:19 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Emails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "EMAILS", schema = "EADDRESS")
//@Table(name = "EMAILS", schema = "ADMIN")
public class Emails implements java.io.Serializable {

	private BigDecimal emailsId;
	private String msisdn;
	private String email;
	private String product;
	private String billcycle;
	private String iscommunicated;
	private String isverified;
	private String interestedforebill;
	private String media;
	private String updateby;
	private Date updatedate;
	private String createdby;
	private Date createddate;

	public Emails() {
	}

	public Emails(BigDecimal emailsId) {
		this.emailsId = emailsId;
	}

	public Emails(BigDecimal emailsId, String msisdn, String email, String product, String billcycle,
			String iscommunicated, String isverified, String interestedforebill, String media, String updateby,
			Date updatedate, String createdby, Date createddate) {
		this.emailsId = emailsId;
		this.msisdn = msisdn;
		this.email = email;
		this.product = product;
		this.billcycle = billcycle;
		this.iscommunicated = iscommunicated;
		this.isverified = isverified;
		this.interestedforebill = interestedforebill;
		this.media = media;
		this.updateby = updateby;
		this.updatedate = updatedate;
		this.createdby = createdby;
		this.createddate = createddate;
	}

	@Id
	//@GeneratedValue(strategy=GenerationType.AUTO)
	@SequenceGenerator(name="email_seq", sequenceName="EMAILS_SEQ")
	@GeneratedValue(strategy = GenerationType.SEQUENCE ,generator="email_seq")
	@Column(name = "EMAILS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getEmailsId() {
		return this.emailsId;
	}

	public void setEmailsId(BigDecimal emailsId) {
		this.emailsId = emailsId;
	}

	@Column(name = "MSISDN", length = 15)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "EMAIL", length = 1000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PRODUCT", length = 15)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "BILLCYCLE", length = 15)
	public String getBillcycle() {
		return this.billcycle;
	}

	public void setBillcycle(String billcycle) {
		this.billcycle = billcycle;
	}

	@Column(name = "ISCOMMUNICATED", length = 10)
	public String getIscommunicated() {
		return this.iscommunicated;
	}

	public void setIscommunicated(String iscommunicated) {
		this.iscommunicated = iscommunicated;
	}

	@Column(name = "ISVERIFIED", length = 10)
	public String getIsverified() {
		return this.isverified;
	}

	public void setIsverified(String isverified) {
		this.isverified = isverified;
	}

	@Column(name = "INTERESTEDFOREBILL", length = 10)
	public String getInterestedforebill() {
		return this.interestedforebill;
	}

	public void setInterestedforebill(String interestedforebill) {
		this.interestedforebill = interestedforebill;
	}

	@Column(name = "MEDIA", length = 200)
	public String getMedia() {
		return this.media;
	}

	public void setMedia(String media) {
		this.media = media;
	}

	@Column(name = "UPDATEBY", length = 100)
	public String getUpdateby() {
		return this.updateby;
	}

	public void setUpdateby(String updateby) {
		this.updateby = updateby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDATE", length = 7)
	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

}
