package com.web.bl.model;
// Generated Jun 12, 2018 2:03:04 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IbRequest generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "IB_REQUEST", schema = "EADDRESS")
//@Table(name = "IB_REQUEST", schema = "ADMIN")
public class IbRequest implements java.io.Serializable {

	private BigDecimal ibRequestId;
	private String msisdn;
	private String billGroup;
	private String year;
	private String month;
	private String emailAddress;
	private String deliveryCharge;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String deliveryType;
	private String status;
	private String completedBy;
	private String remarks;
	private String createdBy;

	public IbRequest() {
	}

	public IbRequest(BigDecimal ibRequestId) {
		this.ibRequestId = ibRequestId;
	}

	public IbRequest(BigDecimal ibRequestId, String msisdn, String billGroup, String year, String month,
			String emailAddress, String deliveryCharge, Date createdDate, String updatedBy, Date updatedDate,
			String deliveryType, String status, String completedBy, String remarks, String createdBy) {
		this.ibRequestId = ibRequestId;
		this.msisdn = msisdn;
		this.billGroup = billGroup;
		this.year = year;
		this.month = month;
		this.emailAddress = emailAddress;
		this.deliveryCharge = deliveryCharge;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.deliveryType = deliveryType;
		this.status = status;
		this.completedBy = completedBy;
		this.remarks = remarks;
		this.createdBy = createdBy;
	}

	@Id

	@Column(name = "IB_REQUEST_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIbRequestId() {
		return this.ibRequestId;
	}

	public void setIbRequestId(BigDecimal ibRequestId) {
		this.ibRequestId = ibRequestId;
	}

	@Column(name = "MSISDN", length = 20)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "BILL_GROUP", length = 20)
	public String getBillGroup() {
		return this.billGroup;
	}

	public void setBillGroup(String billGroup) {
		this.billGroup = billGroup;
	}

	@Column(name = "YEAR", length = 20)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "MONTH", length = 20)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "EMAIL_ADDRESS", length = 200)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "DELIVERY_CHARGE", length = 20)
	public String getDeliveryCharge() {
		return this.deliveryCharge;
	}

	public void setDeliveryCharge(String deliveryCharge) {
		this.deliveryCharge = deliveryCharge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UPDATED_BY", length = 200)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATED_DATE", length = 7)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "DELIVERY_TYPE", length = 50)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMPLETED_BY", length = 100)
	public String getCompletedBy() {
		return this.completedBy;
	}

	public void setCompletedBy(String completedBy) {
		this.completedBy = completedBy;
	}
	
	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}
	
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	@Column(name = "CREATED_BY", length = 200)
	public String getCreatedBy() {
		return this.createdBy;
	}
	
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
