package com.web.bl.model;
// Generated Aug 6, 2018 4:16:57 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmsTemplate generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "SMS_TEMPLATE", schema = "EADDRESS")
//@Table(name = "SMS_TEMPLATE", schema = "ADMIN")
public class SmsTemplate implements java.io.Serializable {

	private BigDecimal smsTmplId;
	private String stText;
	private String stActive;

	public SmsTemplate() {
	}

	public SmsTemplate(BigDecimal smsTmplId) {
		this.smsTmplId = smsTmplId;
	}

	public SmsTemplate(BigDecimal smsTmplId, String stText, String stActive) {
		this.smsTmplId = smsTmplId;
		this.stText = stText;
		this.stActive = stActive;
	}

	@Id

	@Column(name = "SMS_TMPL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSmsTmplId() {
		return this.smsTmplId;
	}

	public void setSmsTmplId(BigDecimal smsTmplId) {
		this.smsTmplId = smsTmplId;
	}

	@Column(name = "ST_TEXT", length = 200)
	public String getStText() {
		return this.stText;
	}

	public void setStText(String stText) {
		this.stText = stText;
	}

	@Column(name = "ST_ACTIVE", length = 10)
	public String getStActive() {
		return this.stActive;
	}

	public void setStActive(String stActive) {
		this.stActive = stActive;
	}

}
