package com.web.bl.model;
// Generated Aug 1, 2018 3:05:00 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uploadpod generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "UPLOADPOD", schema = "EADDRESS")
//@Table(name = "UPLOADPOD", schema = "ADMIN")
public class Uploadpod implements java.io.Serializable {

	private BigDecimal uploadpodId;
	private String category;
	private String contrno;
	private String msisdn;
	private String name;
	private String address;
	private String ibNib;
	private String billCycle;
	private String month;
	private String year;
	private String receivedBy;
	private String relation;
	private Date delReturnDate;
	private String delReturnBy;
	private String returnReason;
	private String status;
	private String courier;

	public Uploadpod() {
	}

	public Uploadpod(BigDecimal uploadpodId) {
		this.uploadpodId = uploadpodId;
	}

	public Uploadpod(BigDecimal uploadpodId, String category, String contrno, String msisdn, String name,
			String address, String ibNib, String billCycle, String month, String year, String receivedBy,
			String relation, Date delReturnDate, String delReturnBy, String returnReason, String status,
			String courier) {
		this.uploadpodId = uploadpodId;
		this.category = category;
		this.contrno = contrno;
		this.msisdn = msisdn;
		this.name = name;
		this.address = address;
		this.ibNib = ibNib;
		this.billCycle = billCycle;
		this.month = month;
		this.year = year;
		this.receivedBy = receivedBy;
		this.relation = relation;
		this.delReturnDate = delReturnDate;
		this.delReturnBy = delReturnBy;
		this.returnReason = returnReason;
		this.status = status;
		this.courier = courier;
	}

	@Id

	@Column(name = "UPLOADPOD_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUploadpodId() {
		return this.uploadpodId;
	}

	public void setUploadpodId(BigDecimal uploadpodId) {
		this.uploadpodId = uploadpodId;
	}

	@Column(name = "CATEGORY", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "CONTRNO", length = 50)
	public String getContrno() {
		return this.contrno;
	}

	public void setContrno(String contrno) {
		this.contrno = contrno;
	}

	@Column(name = "MSISDN", length = 50)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "IB_NIB", length = 50)
	public String getIbNib() {
		return this.ibNib;
	}

	public void setIbNib(String ibNib) {
		this.ibNib = ibNib;
	}

	@Column(name = "BILL_CYCLE", length = 50)
	public String getBillCycle() {
		return this.billCycle;
	}

	public void setBillCycle(String billCycle) {
		this.billCycle = billCycle;
	}

	@Column(name = "MONTH", length = 50)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "YEAR", length = 50)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "RECEIVED_BY", length = 50)
	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Column(name = "RELATION", length = 50)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEL_RETURN_DATE", length = 7)
	public Date getDelReturnDate() {
		return this.delReturnDate;
	}

	public void setDelReturnDate(Date delReturnDate) {
		this.delReturnDate = delReturnDate;
	}

	@Column(name = "DEL_RETURN_BY", length = 50)
	public String getDelReturnBy() {
		return this.delReturnBy;
	}

	public void setDelReturnBy(String delReturnBy) {
		this.delReturnBy = delReturnBy;
	}

	@Column(name = "RETURN_REASON", length = 50)
	public String getReturnReason() {
		return this.returnReason;
	}

	public void setReturnReason(String returnReason) {
		this.returnReason = returnReason;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COURIER", length = 50)
	public String getCourier() {
		return this.courier;
	}

	public void setCourier(String courier) {
		this.courier = courier;
	}

}
