package com.web.bl.model;
// Generated Jun 3, 2018 11:54:15 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usergrouppageaccess generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USERGROUPPAGEACCESS", schema = "EADDRESS")
//@Table(name = "USERGROUPPAGEACCESS", schema = "ADMIN")
public class Usergrouppageaccess implements java.io.Serializable {

	private BigDecimal usergrouppageaccessid;
	private Usergroup usergroup;
	private Usergrouppage usergrouppage;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Usergrouppageaccess() {
	}

	public Usergrouppageaccess(BigDecimal usergrouppageaccessid, Usergroup usergroup, Usergrouppage usergrouppage) {
		this.usergrouppageaccessid = usergrouppageaccessid;
		this.usergroup = usergroup;
		this.usergrouppage = usergrouppage;
	}

	public Usergrouppageaccess(BigDecimal usergrouppageaccessid, Usergroup usergroup, Usergrouppage usergrouppage,
			String active, String createdby, Date createddate, String updatedby, Date updateddate) {
		this.usergrouppageaccessid = usergrouppageaccessid;
		this.usergroup = usergroup;
		this.usergrouppage = usergrouppage;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	@Id

	@Column(name = "USERGROUPPAGEACCESSID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsergrouppageaccessid() {
		return this.usergrouppageaccessid;
	}

	public void setUsergrouppageaccessid(BigDecimal usergrouppageaccessid) {
		this.usergrouppageaccessid = usergrouppageaccessid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERGROUPID", nullable = false)
	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERGROUPPAGEID", nullable = false)
	public Usergrouppage getUsergrouppage() {
		return this.usergrouppage;
	}

	public void setUsergrouppage(Usergrouppage usergrouppage) {
		this.usergrouppage = usergrouppage;
	}

	@Column(name = "ACTIVE", length = 50)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
