package com.web.bl.model;
// Generated Jun 3, 2018 11:54:15 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Usergroup generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USERGROUP", schema = "EADDRESS")
//@Table(name = "USERGROUP", schema = "ADMIN")
public class Usergroup implements java.io.Serializable {

	private BigDecimal usergroupid;
	private String name;
	private String section;
	private String department;
	private String division;
	private String emailid;
	private String escalationemailid;
	private String code;
	private String alliesname;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;
	private Set<Usergrouppageaccess> usergrouppageaccesses = new HashSet<Usergrouppageaccess>(0);
	private Set<Userandusergroupmap> userandusergroupmaps = new HashSet<Userandusergroupmap>(0);

	public Usergroup() {
	}

	public Usergroup(BigDecimal usergroupid, String name) {
		this.usergroupid = usergroupid;
		this.name = name;
	}

	public Usergroup(BigDecimal usergroupid, String name, String section, String department, String division,
			String emailid, String escalationemailid, String code, String alliesname, String active, String createdby,
			Date createddate, String updatedby, Date updateddate, Set<Usergrouppageaccess> usergrouppageaccesses,
			Set<Userandusergroupmap> userandusergroupmaps) {
		this.usergroupid = usergroupid;
		this.name = name;
		this.section = section;
		this.department = department;
		this.division = division;
		this.emailid = emailid;
		this.escalationemailid = escalationemailid;
		this.code = code;
		this.alliesname = alliesname;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.usergrouppageaccesses = usergrouppageaccesses;
		this.userandusergroupmaps = userandusergroupmaps;
	}

	@Id

	@Column(name = "USERGROUPID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsergroupid() {
		return this.usergroupid;
	}

	public void setUsergroupid(BigDecimal usergroupid) {
		this.usergroupid = usergroupid;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SECTION", length = 100)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "DEPARTMENT", length = 200)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "DIVISION", length = 200)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "EMAILID", length = 1000)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "ESCALATIONEMAILID", length = 1000)
	public String getEscalationemailid() {
		return this.escalationemailid;
	}

	public void setEscalationemailid(String escalationemailid) {
		this.escalationemailid = escalationemailid;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "ALLIESNAME", length = 100)
	public String getAlliesname() {
		return this.alliesname;
	}

	public void setAlliesname(String alliesname) {
		this.alliesname = alliesname;
	}

	@Column(name = "ACTIVE", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergroup")
	@JsonIgnore
	public Set<Usergrouppageaccess> getUsergrouppageaccesses() {
		return this.usergrouppageaccesses;
	}

	public void setUsergrouppageaccesses(Set<Usergrouppageaccess> usergrouppageaccesses) {
		this.usergrouppageaccesses = usergrouppageaccesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergroup")
	@JsonIgnore
	public Set<Userandusergroupmap> getUserandusergroupmaps() {
		return this.userandusergroupmaps;
	}

	public void setUserandusergroupmaps(Set<Userandusergroupmap> userandusergroupmaps) {
		this.userandusergroupmaps = userandusergroupmaps;
	}

}
