package com.web.bl.model;
// Generated Jun 3, 2018 11:54:15 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userandusergroupmap generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USERANDUSERGROUPMAP", schema = "EADDRESS")
//@Table(name = "USERANDUSERGROUPMAP", schema = "ADMIN")
public class Userandusergroupmap implements java.io.Serializable {

	private BigDecimal userandusergroupmapid;
	private Users users;
	private Usergroup usergroup;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Userandusergroupmap() {
	}

	public Userandusergroupmap(BigDecimal userandusergroupmapid) {
		this.userandusergroupmapid = userandusergroupmapid;
	}

	public Userandusergroupmap(BigDecimal userandusergroupmapid, Users users, Usergroup usergroup, String active,
			String createdby, Date createddate, String updatedby, Date updateddate) {
		this.userandusergroupmapid = userandusergroupmapid;
		this.users = users;
		this.usergroup = usergroup;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	@Id

	@Column(name = "USERANDUSERGROUPMAPID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserandusergroupmapid() {
		return this.userandusergroupmapid;
	}

	public void setUserandusergroupmapid(BigDecimal userandusergroupmapid) {
		this.userandusergroupmapid = userandusergroupmapid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERID")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERGROUPID")
	public Usergroup getUsergroup() {
		return this.usergroup;
	}

	public void setUsergroup(Usergroup usergroup) {
		this.usergroup = usergroup;
	}

	@Column(name = "ACTIVE", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 20)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 20)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
