package com.web.bl.model;
// Generated Jun 3, 2018 11:54:15 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Usergrouppage generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USERGROUPPAGE", schema = "EADDRESS")
//@Table(name = "USERGROUPPAGE", schema = "ADMIN")
public class Usergrouppage implements java.io.Serializable {

	private BigDecimal usergrouppageid;
	private String name;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;
	private Set<Usergrouppageaccess> usergrouppageaccesses = new HashSet<Usergrouppageaccess>(0);

	public Usergrouppage() {
	}

	public Usergrouppage(BigDecimal usergrouppageid, String name) {
		this.usergrouppageid = usergrouppageid;
		this.name = name;
	}

	public Usergrouppage(BigDecimal usergrouppageid, String name, String active, String createdby, Date createddate,
			String updatedby, Date updateddate, Set<Usergrouppageaccess> usergrouppageaccesses) {
		this.usergrouppageid = usergrouppageid;
		this.name = name;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.usergrouppageaccesses = usergrouppageaccesses;
	}

	@Id

	@Column(name = "USERGROUPPAGEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsergrouppageid() {
		return this.usergrouppageid;
	}

	public void setUsergrouppageid(BigDecimal usergrouppageid) {
		this.usergrouppageid = usergrouppageid;
	}

	@Column(name = "NAME", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ACTIVE", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usergrouppage")
	@JsonIgnore
	public Set<Usergrouppageaccess> getUsergrouppageaccesses() {
		return this.usergrouppageaccesses;
	}

	public void setUsergrouppageaccesses(Set<Usergrouppageaccess> usergrouppageaccesses) {
		this.usergrouppageaccesses = usergrouppageaccesses;
	}

}
