package com.web.bl.model;
// Generated May 27, 2018 12:58:26 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "EADDRESS")
//@Table(name = "USERS", schema = "ADMIN")
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal userid;
	private Usercategory usercategory;
	private String networkid;
	private String name;
	private String designation;
	private String location;
	private String emailid;
	private String msisdn;
	private String roletype;
	private String password;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;

	public Users() {
	}

	public Users(BigDecimal userid, Usercategory usercategory, String networkid, String emailid, String msisdn,
			String roletype, String password, String active) {
		this.userid = userid;
		this.usercategory = usercategory;
		this.networkid = networkid;
		this.emailid = emailid;
		this.msisdn = msisdn;
		this.roletype = roletype;
		this.password = password;
		this.active = active;
	}

	public Users(BigDecimal userid, Usercategory usercategory, String networkid, String name, String designation,
			String location, String emailid, String msisdn, String roletype, String password, String active,
			String createdby, Date createddate, String updatedby, Date updateddate) {
		this.userid = userid;
		this.usercategory = usercategory;
		this.networkid = networkid;
		this.name = name;
		this.designation = designation;
		this.location = location;
		this.emailid = emailid;
		this.msisdn = msisdn;
		this.roletype = roletype;
		this.password = password;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
	}

	@Id
	
	@Column(name = "USERID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserid() {
		return this.userid;
	}

	public void setUserid(BigDecimal userid) {
		this.userid = userid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERCATEGORYID")
	public Usercategory getUsercategory() {
		return this.usercategory;
	}

	public void setUsercategory(Usercategory usercategory) {
		this.usercategory = usercategory;
	}

	@Column(name = "NETWORKID", length = 100)
	public String getNetworkid() {
		return this.networkid;
	}

	public void setNetworkid(String networkid) {
		this.networkid = networkid;
	}

	@Column(name = "NAME", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESIGNATION", length = 300)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "LOCATION", length = 300)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "EMAILID", length = 100)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "MSISDN", length = 100)
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "ROLETYPE", length = 100)
	public String getRoletype() {
		return this.roletype;
	}

	public void setRoletype(String roletype) {
		this.roletype = roletype;
	}

	@Column(name = "PASSWORD", length = 300)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ACTIVE", length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

}
