package com.web.bl.model;
// Generated Jun 3, 2018 11:54:15 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Usercategory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USERCATEGORY", schema = "EADDRESS")
//@Table(name = "USERCATEGORY", schema = "ADMIN")
public class Usercategory implements java.io.Serializable {

	private BigDecimal usercategoryid;
	private String name;
	private String active;
	private String createdby;
	private Date createddate;
	private String updatedby;
	private Date updateddate;
	private Set<Users> userses = new HashSet<Users>(0);

	public Usercategory() {
	}

	public Usercategory(BigDecimal usercategoryid) {
		this.usercategoryid = usercategoryid;
	}

	public Usercategory(BigDecimal usercategoryid, String name, String active, String createdby, Date createddate,
			String updatedby, Date updateddate, Set<Users> userses) {
		this.usercategoryid = usercategoryid;
		this.name = name;
		this.active = active;
		this.createdby = createdby;
		this.createddate = createddate;
		this.updatedby = updatedby;
		this.updateddate = updateddate;
		this.userses = userses;
	}

	@Id

	@Column(name = "USERCATEGORYID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUsercategoryid() {
		return this.usercategoryid;
	}

	public void setUsercategoryid(BigDecimal usercategoryid) {
		this.usercategoryid = usercategoryid;
	}

	@Column(name = "NAME", length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ACTIVE", length = 50)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "CREATEDBY", length = 100)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "UPDATEDBY", length = 100)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATEDDATE", length = 7)
	public Date getUpdateddate() {
		return this.updateddate;
	}

	public void setUpdateddate(Date updateddate) {
		this.updateddate = updateddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usercategory")
	@JsonIgnore
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
